// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dns.proto

package dns

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Record struct {
	// Domain name to insert (FQDN, terminated with .)
	Domain string `protobuf:"bytes,1,opt,name=domain" json:"domain,omitempty"`
	// Time-to-live in seconds
	Ttl uint32 `protobuf:"varint,2,opt,name=ttl" json:"ttl,omitempty"`
	// Class ("IN" most likely)
	Class string `protobuf:"bytes,3,opt,name=class" json:"class,omitempty"`
	// Type (any case, e.g. "A", "AAAA", etc.)
	Type string `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	// Data of the record
	Data                 string   `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_dns_5b06c79e2be448d9, []int{0}
}
func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (dst *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(dst, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Record) GetTtl() uint32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

func (m *Record) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *Record) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Record) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type InsertRequest struct {
	Record               []*Record `protobuf:"bytes,1,rep,name=record" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *InsertRequest) Reset()         { *m = InsertRequest{} }
func (m *InsertRequest) String() string { return proto.CompactTextString(m) }
func (*InsertRequest) ProtoMessage()    {}
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dns_5b06c79e2be448d9, []int{1}
}
func (m *InsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertRequest.Unmarshal(m, b)
}
func (m *InsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertRequest.Marshal(b, m, deterministic)
}
func (dst *InsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertRequest.Merge(dst, src)
}
func (m *InsertRequest) XXX_Size() int {
	return xxx_messageInfo_InsertRequest.Size(m)
}
func (m *InsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InsertRequest proto.InternalMessageInfo

func (m *InsertRequest) GetRecord() []*Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type RemoveRequest struct {
	Record               []*Record `protobuf:"bytes,1,rep,name=record" json:"record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RemoveRequest) Reset()         { *m = RemoveRequest{} }
func (m *RemoveRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveRequest) ProtoMessage()    {}
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dns_5b06c79e2be448d9, []int{2}
}
func (m *RemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveRequest.Unmarshal(m, b)
}
func (m *RemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveRequest.Marshal(b, m, deterministic)
}
func (dst *RemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveRequest.Merge(dst, src)
}
func (m *RemoveRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveRequest.Size(m)
}
func (m *RemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveRequest proto.InternalMessageInfo

func (m *RemoveRequest) GetRecord() []*Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type InsertResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InsertResponse) Reset()         { *m = InsertResponse{} }
func (m *InsertResponse) String() string { return proto.CompactTextString(m) }
func (*InsertResponse) ProtoMessage()    {}
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dns_5b06c79e2be448d9, []int{3}
}
func (m *InsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InsertResponse.Unmarshal(m, b)
}
func (m *InsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InsertResponse.Marshal(b, m, deterministic)
}
func (dst *InsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InsertResponse.Merge(dst, src)
}
func (m *InsertResponse) XXX_Size() int {
	return xxx_messageInfo_InsertResponse.Size(m)
}
func (m *InsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InsertResponse proto.InternalMessageInfo

type RemoveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveResponse) Reset()         { *m = RemoveResponse{} }
func (m *RemoveResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveResponse) ProtoMessage()    {}
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dns_5b06c79e2be448d9, []int{4}
}
func (m *RemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveResponse.Unmarshal(m, b)
}
func (m *RemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveResponse.Marshal(b, m, deterministic)
}
func (dst *RemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveResponse.Merge(dst, src)
}
func (m *RemoveResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveResponse.Size(m)
}
func (m *RemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Record)(nil), "dns.Record")
	proto.RegisterType((*InsertRequest)(nil), "dns.InsertRequest")
	proto.RegisterType((*RemoveRequest)(nil), "dns.RemoveRequest")
	proto.RegisterType((*InsertResponse)(nil), "dns.InsertResponse")
	proto.RegisterType((*RemoveResponse)(nil), "dns.RemoveResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DynamicDnsServiceClient is the client API for DynamicDnsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DynamicDnsServiceClient interface {
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
}

type dynamicDnsServiceClient struct {
	cc *grpc.ClientConn
}

func NewDynamicDnsServiceClient(cc *grpc.ClientConn) DynamicDnsServiceClient {
	return &dynamicDnsServiceClient{cc}
}

func (c *dynamicDnsServiceClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, "/dns.DynamicDnsService/Insert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicDnsServiceClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, "/dns.DynamicDnsService/Remove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamicDnsServiceServer is the server API for DynamicDnsService service.
type DynamicDnsServiceServer interface {
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
}

func RegisterDynamicDnsServiceServer(s *grpc.Server, srv DynamicDnsServiceServer) {
	s.RegisterService(&_DynamicDnsService_serviceDesc, srv)
}

func _DynamicDnsService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicDnsServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dns.DynamicDnsService/Insert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicDnsServiceServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicDnsService_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicDnsServiceServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dns.DynamicDnsService/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicDnsServiceServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DynamicDnsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dns.DynamicDnsService",
	HandlerType: (*DynamicDnsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Insert",
			Handler:    _DynamicDnsService_Insert_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _DynamicDnsService_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dns.proto",
}

func init() { proto.RegisterFile("dns.proto", fileDescriptor_dns_5b06c79e2be448d9) }

var fileDescriptor_dns_5b06c79e2be448d9 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x91, 0xbb, 0x4e, 0xc3, 0x30,
	0x14, 0x86, 0x5b, 0xd2, 0x5a, 0xea, 0xa9, 0x8a, 0xca, 0x01, 0x21, 0x8b, 0x09, 0x85, 0xa5, 0x53,
	0x87, 0x96, 0x47, 0xe8, 0xc2, 0x6a, 0x9e, 0xc0, 0xc4, 0x67, 0x88, 0xd4, 0xd8, 0xc6, 0x36, 0x95,
	0x3a, 0xf0, 0xee, 0xf8, 0xd6, 0xc1, 0x23, 0xdb, 0x7f, 0xbe, 0xe4, 0xbf, 0x48, 0x86, 0x95, 0xd2,
	0x7e, 0x6f, 0x9d, 0x09, 0x06, 0xbb, 0x28, 0x7b, 0x0b, 0x4c, 0xd0, 0x60, 0x9c, 0xc2, 0x67, 0x60,
	0xca, 0x4c, 0x72, 0xd4, 0x7c, 0xfe, 0x3a, 0xdf, 0xad, 0x44, 0xbd, 0x70, 0x0b, 0x5d, 0x08, 0x67,
	0x7e, 0x17, 0xe1, 0x46, 0x24, 0x89, 0x4f, 0xb0, 0x1c, 0xce, 0xd2, 0x7b, 0xde, 0xe5, 0x1f, 0xcb,
	0x81, 0x08, 0x8b, 0x70, 0xb5, 0xc4, 0x17, 0x19, 0x66, 0x9d, 0x98, 0x92, 0x41, 0xf2, 0x65, 0x61,
	0x49, 0xf7, 0xef, 0xb0, 0xf9, 0xd0, 0x9e, 0x5c, 0x10, 0xf4, 0xfd, 0x43, 0x3e, 0xe0, 0x1b, 0x30,
	0x97, 0x27, 0xc4, 0xe2, 0x6e, 0xb7, 0x3e, 0xac, 0xf7, 0x69, 0x63, 0x59, 0x25, 0xea, 0xa7, 0xe4,
	0x12, 0x34, 0x99, 0x0b, 0xfd, 0xcb, 0xb5, 0x85, 0xfb, 0x5b, 0x97, 0xb7, 0x26, 0xaa, 0x44, 0x6e,
	0x39, 0x85, 0x1c, 0x7e, 0xe1, 0xe1, 0x74, 0xd5, 0x72, 0x1a, 0x87, 0x93, 0xf6, 0x9f, 0xe4, 0x2e,
	0xe3, 0x40, 0x78, 0x04, 0x56, 0x8c, 0x88, 0x39, 0xb7, 0x59, 0xfc, 0xf2, 0xd8, 0xb0, 0x9a, 0x3c,
	0x4b, 0xa6, 0x92, 0x5d, 0x4d, 0xcd, 0xe0, 0x6a, 0x6a, 0xcb, 0xfb, 0xd9, 0x17, 0xcb, 0x8f, 0x71,
	0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xeb, 0xf0, 0x57, 0x99, 0x01, 0x00, 0x00,
}
