// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal.proto

package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Contains all facts known about the verified user
type VerifiedUser struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	Group                []string `protobuf:"bytes,4,rep,name=group" json:"group,omitempty"`
	ReverseDns           string   `protobuf:"bytes,5,opt,name=reverse_dns,json=reverseDns" json:"reverse_dns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifiedUser) Reset()         { *m = VerifiedUser{} }
func (m *VerifiedUser) String() string { return proto.CompactTextString(m) }
func (*VerifiedUser) ProtoMessage()    {}
func (*VerifiedUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_aad17d748c6438b3, []int{0}
}
func (m *VerifiedUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifiedUser.Unmarshal(m, b)
}
func (m *VerifiedUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifiedUser.Marshal(b, m, deterministic)
}
func (dst *VerifiedUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifiedUser.Merge(dst, src)
}
func (m *VerifiedUser) XXX_Size() int {
	return xxx_messageInfo_VerifiedUser.Size(m)
}
func (m *VerifiedUser) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifiedUser.DiscardUnknown(m)
}

var xxx_messageInfo_VerifiedUser proto.InternalMessageInfo

func (m *VerifiedUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *VerifiedUser) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *VerifiedUser) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *VerifiedUser) GetGroup() []string {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *VerifiedUser) GetReverseDns() string {
	if m != nil {
		return m.ReverseDns
	}
	return ""
}

func init() {
	proto.RegisterType((*VerifiedUser)(nil), "auth.VerifiedUser")
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor_internal_aad17d748c6438b3) }

var fileDescriptor_internal_aad17d748c6438b3 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x49, 0x2c, 0x2d, 0xc9,
	0x50, 0x6a, 0x65, 0xe4, 0xe2, 0x09, 0x4b, 0x2d, 0xca, 0x4c, 0xcb, 0x4c, 0x4d, 0x09, 0x2d, 0x4e,
	0x2d, 0x12, 0x92, 0xe2, 0xe2, 0x28, 0x2d, 0x06, 0xa9, 0xcb, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x82, 0xf3, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x0b, 0x24, 0x98, 0xc0, 0xa2, 0x4c, 0x99,
	0x05, 0x42, 0x42, 0x5c, 0x2c, 0x05, 0xf9, 0x45, 0x25, 0x12, 0xcc, 0x60, 0x11, 0x30, 0x5b, 0x48,
	0x84, 0x8b, 0x35, 0xbd, 0x28, 0xbf, 0xb4, 0x40, 0x82, 0x45, 0x81, 0x59, 0x83, 0x33, 0x08, 0xc2,
	0x11, 0x92, 0xe7, 0xe2, 0x2e, 0x4a, 0x2d, 0x4b, 0x2d, 0x2a, 0x4e, 0x8d, 0x4f, 0xc9, 0x2b, 0x96,
	0x60, 0x05, 0x6b, 0xe0, 0x82, 0x0a, 0xb9, 0xe4, 0x15, 0x27, 0xb1, 0x81, 0x1d, 0x65, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xf4, 0x9b, 0x7c, 0x96, 0xa6, 0x00, 0x00, 0x00,
}
